id: PAA35CEAB
initial_creation_type: ocr
source_metadata:
  volumes:
    0858b80b34174e42ad08bdb3aa6d659b:
      base_file: v074.txt
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་གཞི་བསྡུ་བ།
      total_pages: 1618
      volume_number: 74
